# Generated by Django 4.1.1 on 2023-12-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_email', models.CharField(blank=True, max_length=100)),
                ('user_mobile', models.CharField(blank=True, max_length=100)),
                ('user_password', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'user_table',
                'managed': True,
            },
        ),
    ]
