# Generated by Django 4.1.1 on 2023-12-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(blank=True, max_length=200)),
                ('img_type', models.CharField(blank=True, max_length=100)),
                ('image_path', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
            options={
                'db_table': 'user_img_table',
                'managed': True,
            },
        ),
    ]
