# Generated by Django 4.1.1 on 2023-12-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
