# Generated by Django 4.1.1 on 2023-12-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code/'),
        ),
    ]
